import "../styles/Template.css";
import { useLocation } from "react-router-dom";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import html2pdf from "html2pdf.js";
import { faEnvelope,faHouse, faPhone } from '@fortawesome/free-solid-svg-icons';



function Template() {
  const location = useLocation();

    const billData = location.state;

    if (!billData) {
        return <center>No invoice data found.</center>;
    }

  
  const {
    comp_name,
    comp_address,
    comp_phone,
    comp_email,
    logo,
    services,
    gender,
    recp_name,
    recp_address,
    recp_no,
    date1,
    time1,
    employee,
    pay_opt,
    items,
  } = billData;

   const invoiceNo =
  "INV-" +
  new Date().getFullYear() +
  "-" +
  Math.floor(Math.random() * 10000);

  const subTotal = items.reduce(
    (sum, item) => sum + item.qty * item.price,
    0
  );

  const gstRate = 18;
  const gstAmount = (subTotal * gstRate) / 100;
  const cgst = gstAmount / 2;
  const sgst = gstAmount / 2;
  const grandTotal = subTotal + gstAmount;

  const downloadPDF = () => {
  const element = document.querySelector(".invoice");

    const opt = {
  margin: 0,
  filename: `${invoiceNo}.pdf`,
  image: {
    type: "jpeg",
    quality: 1,
  },
  html2canvas: {
    scale: 2,
    useCORS: true,
  },
  jsPDF: {
    unit: "mm",
    format: "a4",
    orientation: "portrait",
  },
};

html2pdf().set(opt).from(document.querySelector(".invoice")).save();
};
const createPDF=async()=>{
  await fetch(
  "http://localhost:5000/api/pdf/generate-pdf",
  {
  method:"POST",
  headers:{
  "Content-Type":"application/json"
  },
  body:JSON.stringify({
  html:html
  })
  }
);

alert("PDF Saved");

}
  return (
    <>
      <div className="invoice-actions">
        <button onClick={downloadPDF}>Download PDF</button>
        <button onClick={createPDF}>Save PDF</button>
      </div>

      <div className="invoice">
        <div className="invoice-header">
          <div className="company">
            <div className="logo2">
              <img src={logo ? URL.createObjectURL(logo) : ""} alt="logo" />
              <div className="desc">
                <h1>{comp_name}</h1>
                <h4>{services}</h4>
              </div>
            </div>
            <div className="contact_info">
                <p><FontAwesomeIcon icon={faHouse} />   {comp_address}</p>
                <p><FontAwesomeIcon icon={faPhone}/>    {comp_phone}</p>
                <p><FontAwesomeIcon icon={faEnvelope}/> {comp_email}</p>
            </div>

          </div>

          <div className="invoice-title">
            <h2>INVOICE</h2>
          </div>
        </div>
       
        <div className="invoice_body">
          <div className="invoice-row">
            <div className="bill-to">
              <h3>Billed To</h3>

              <p>
                {gender} {recp_name}
              </p>

              <p>{recp_address}</p>

              <p>{recp_no}</p>
            </div>

            <div className="invoice-info">
              <p>Invoice No : {invoiceNo}</p>
              <p>Invoice Date : {date1}</p>
              <p>Invoice Time : {time1}</p>
              <p>Generated By : {employee}</p>
              <p>Payment : {pay_opt}</p>
            </div>
          </div>

          <table className="invoice-table">
            <thead>
              <tr>
                <th>S.No</th>
                <th>Description</th>
                <th>Qty</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>

            <tbody>
              {items.map((item, index) => (
                <tr key={index}>
                  <td>{index + 1}</td>

                  <td>{item.itemName}</td>

                  <td>{item.qty}</td>

                  <td>{item.price}</td>

                  <td>{item.qty * item.price}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="invoice-footer">
            <div className="bank-details">
              <h3>Bank Details</h3>

              <p>Bank Name : SBI</p>

              <p>Account No : XXXXXXXX</p>

              <p>IFSC : XXXXX</p>
            </div>

            <div className="totals">
                <p>Sub Total : ₹{subTotal}</p>

                <p>CGST (9%) : ₹{cgst.toFixed(2)}</p>

                <p>SGST (9%) : ₹{sgst.toFixed(2)}</p>

                <p>GST Total : ₹{gstAmount.toFixed(2)}</p>

                <h3>Grand Total :<span id="tot">₹{grandTotal.toFixed(2)}</span></h3>
            </div>
          </div>
        </div>
        <footer>
          <h1>Thank you for choosing us ❤️ !!!</h1>
        </footer>
      </div>
    </>
  );
}
export default Template;
